name: CICD

on:
  workflow_dispatch:
    branches: [main]
  push:
    branches: [main]

jobs:
  lint-build-deploy:
    name: Lint, test, and build
    runs-on: ubuntu-latest
    container: zaksabeast/devkit3ds-rust
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nightly rust
        run: rustup default nightly

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Build
        run: make release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: friends-sysmodule
          retention-days: 1
          path: |
            out/release

      - name: Draft release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            out/release
